baseurl = "https://oliviergimenez.github.io"
title = ""
copyright = "&copy; 2017 Olivier Gimenez"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = "https-oliviergimenez-github-io"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-96999184-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Olivier Gimenez"
  role = ""
  organization = ""
  organization_url = ""
  avatar = "flyfishing.jpg"
  email = "olivier.gimenez@cefe.cnrs.fr"
  address = "CEFE UMR 5175, 1919 Route de Mende, 34293 Montpellier, France"
  phone = "+33(0)467613314"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Highlight.js options
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = []
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:olivier.gimenez@cefe.cnrs.fr"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "//scholar.google.fr/citations?hl=fr&user=5NkQUA8AAAAJ&view_op=list_works&sortby=pubdate"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "//www.researchgate.net/profile/Olivier_Gimenez"

  [[params.social]]
    icon = "figshare"
    icon_pack = "ai"
    link = "//figshare.com/authors/_/3914297"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/oaggimenez"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/oliviergimenez"

  [[params.social]]
    icon = "facebook"
    icon_pack = "fa"
    link = "//www.facebook.com/groups/464518943663021/"


# Navigation Links

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "People"
  url = "#People"
  weight = 2

[[menu.main]]
  name = "Current"
  parent = "People"
  url = "#current"
weight = 3

[[menu.main]]
  name = "Former"
  parent = "People"
  url = "#alumni"
weight = 4

[[menu.main]]
  name = "News"
  url = "#news"
  weight = 5

[[menu.main]]
  name = "Publications"
  url = "#publications"
  identifier = "pubs"
  weight = 6
  
[[menu.main]]
  name = "Papers"
  parent = "pubs"
  url = "#papers"
  weight = 7
  
[[menu.main]]
  name = "Books"
  parent = "pubs"
url = "#books"
  weight = 8

  [[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 9


# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
